# Generated by Django 4.1.13 on 2024-08-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ChatBot", "0002_alter_question_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="answer_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="answered_by",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="level",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
