# Generated by Django 4.1.13 on 2024-07-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_gender_user_passport_id_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passport_id',
            field=models.CharField(max_length=10, unique=True, verbose_name='Passport ID'),
        ),
    ]
