# Generated by Django 4.1.13 on 2024-07-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_passport_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='additional_field_mentor',
        ),
        migrations.RemoveField(
            model_name='student',
            name='additional_field_student',
        ),
        migrations.RemoveField(
            model_name='user',
            name='app_rating',
        ),
        migrations.RemoveField(
            model_name='user',
            name='level',
        ),
        migrations.AddField(
            model_name='mentor',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Student Level'),
        ),
    ]
