# Generated by Django 4.1.13 on 2024-07-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBot', '0001_initial'),
        ('users', '0005_remove_mentor_additional_field_mentor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_questions',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='ChatBot.question'),
        ),
    ]
