# Generated by Django 4.1.13 on 2024-08-05 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_helprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.mentor'),
        ),
    ]
