# Generated by Django 4.1.13 on 2024-08-05 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_helprequest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helprequest',
            name='user',
        ),
    ]
