# Generated by Django 4.1.13 on 2024-08-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_helprequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
