# Generated by Django 4.1.13 on 2024-08-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_studentmentorrequest_student_mentor_responsible"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="rating",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
