# Generated by Django 4.1.13 on 2024-08-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_student_mentor_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="level_updated",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
