# Generated by Django 4.1.13 on 2024-08-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_student_level_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notification_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="notifications",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
